version: '2.2'

services:
  nginx:
    build:
        dockerfile: ./nginx-proxy/nginx.dockerfile
        context: .
    image: andresons/nginx
    container_name: nginx
    ports:
        - "80:80"
    networks:
      production-network:
        ipv4_address: "172.22.0.5"
    depends_on:
      - node1
      - node2
      - node3

  node1:
    build:
      dockerfile: mail-example.dockerfile
      context: ./mail-example/
    image: asouza/mail-example
    container_name: mail-example
    networks:
      production-network:
        ipv4_address: "172.22.0.2"
    ports:
      - "3000:3000"

  node2:
    build:
      dockerfile: app-example.dockerfile
      context: ./app-example/
    image: asouza/app-example
    container_name: app-example
    networks:
      production-network:
        ipv4_address: "172.22.0.3"
    ports:
      - "3001:3001"

  node3:
    build:
      dockerfile: api-example.dockerfile
      context: ./api-example/
    image: asouza/api-example
    container_name: api-example
    networks:
      production-network:
        ipv4_address: "172.22.0.4"
    ports:
      - "3002:3002"

networks:
  production-network:
    driver: bridge
    ipam:
      config:
        - subnet: "172.22.0.0/16"
          gateway: "172.22.0.1"
