version: '2.2'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx-proxy/conf.d:/etc/nginx/conf.d:ro
    ports:
        - "80:80"
    depends_on:
      - node1
      - node2
      - node3

  node1:
    build:
      dockerfile: mail-example.dockerfile
      context: ./mail-example/
    image: asouza/mail-example

  node2:
    build:
      dockerfile: app-example.dockerfile
      context: ./app-example/
    image: asouza/app-example

  node3:
    build:
      dockerfile: api-example.dockerfile
      context: ./api-example/
    image: asouza/api-example
